### ISSUE TITLE
Weird lines sometimes appear on map when moving the camera

### ISSUE THREAD

**Issue by Johannes-Larsson** [Dreamteam2015-LBSLund/Village-Tycoon-RTS#6]
Most likely we need to round the camera position to some degree.

**Comment by Johannes-Larsson** [comment]
Actually we need to move the tile textures one pixel away from each other.

**Comment by Johannes-Larsson** [comment]
..and also pad them with their color, since the textureregion isn't always completely accurate.

:+1:

**Comment by indietom** [comment]
:+1:  :+1:
