### ISSUE TITLE
Weird things with pathfinding

### ISSUE THREAD

**Issue by Johannes-Larsson** [Dreamteam2015-LBSLund/Village-Tycoon-RTS#9]
När flera enheter är markerade händer det massa konstiga grejer när man högerklickar på markerade enheter. Vissa enheter slutar röra sig men avmarkeras inte, och resten av enheterna flyttar sig inte dit man klickade.

**Comment by indietom** [comment]
Om deras punkt hamnar på en tile de inte kan gå på så rör de sig inte.

**Comment by Johannes-Larsson** [comment]
Du har fel

**Comment by indietom** [comment]
Fixat och klart :+1:  :+1:  :+1:  :+1: :+1:  :construction_worker:  :construction_worker:  :construction_worker: endast tillsmans är vi starka
